config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
    # @members = %w[alex betty cindy diane eric benjamin charly anthony arthur adele daniel ellen ephraim kate stephan].sort

    # if params[:member]
    #   @members = @members.select { |member| member.start_with?(params[:member])}
    # end

    @members = [
      { first: 'alexa', last: 'brewer' },
      { first: 'bernardette', last: 'collins' },
      { first: 'chloe', last: 'daniels' },
      { first: 'diane', last: 'young' }
    ]

    if params[:first] || params[:last]
      @members = @members.select do |member|
        member[:first].start_with?(params[:first]) || member[:last].start_with?(params[:last])
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvcTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae animi reprehenderit autem fugit error nemo itaque? Ipsam ex aliquid ipsa suscipit possimus praesentium iste error minus atque, optio voluptas vel doloribus nesciunt? Rerum perspiciatis rem quasi aperiam qui perferendis, dolorum doloribus facilis voluptatem blanditiis expedita recusandae debitis dolores modi animi saepe asperiores suscipit. Amet nam delectus minima dolore, voluptates suscipit inventore quod fuga voluptatum accusamus veritatis in dignissimos optio ipsa modi, ipsam dolores voluptatibus laborum explicabo doloribus, facilis cumque ab consequuntur? Aliquam nisi deleniti perferendis iure, dolorum vero delectus accusamus dignissimos? Perspiciatis sequi incidunt id consequuntur. Placeat quod quidem quos blanditiis alias et natus perferendis pariatur sapiente ex ullam minima nam enim, similique eius. Nisi, perferendis sapiente? Explicabo eligendi fugit dolorem inventore dolor id unde enim nemo itaque, officia quasi quia placeat quidem magni numquam quas exercitationem debitis, atque ipsum aliquid? Accusamus magnam tenetur sed sunt laborum culpa, iusto commodi expedita impedit similique vel harum vero odio repudiandae sapiente porro quae ab esse repellendus mollitia explicabo! Nisi ullam reprehenderit id fugit vitae, magni nihil veniam corporis numquam velit beatae dolorum qui! Eius sapiente eligendi nisi omnis, aut, ad ipsa quis quibusdam architecto ipsam eaque perferendis laborum velit doloremque eum molestias iste veniam expedita. Consequuntur iste esse voluptatem earum quis alias aliquid nesciunt sint debitis consectetur possimus facere, accusantium eveniet nostrum maxime minima nulla est porro quo repudiandae itaque sequi dolor velit. Vitae ratione beatae autem iure maxime eaque cupiditate labore. Fugiat nemo omnis dolorum vel incidunt qui ut, expedita, explicabo quo quae unde molestiae magni obcaecati?</p>

<%= link_to 'Back home', root_path %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

<ul>
  <% @members.each do |member| %>
    <li>
      <%= member[:first].capitalize %> <%= member[:last].capitalize %>
    </li>
  <% end %>
</ul>

<form action="/contact" method="get">
  <input
    type="text"
    name="first"
    placeholder="Who are you looking for?"
    value="<%= params[:first] %>"
  >
  <input
    type="text"
    name="last"
    placeholder="Who are you looking for?"
    value="<%= params[:last] %>"
  >
  <input type="submit">
</form>

<%= link_to 'Back home', root_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'Know more about us', about_path %>
<%= link_to 'Meet our team', contact_path %>